#!/bin/bash

# This script configures Nginx on an Arch Linux system to add a custom HTTP response header indicating the server hostname.

sudo pacman -Syu

sudo pacman -S --noconfirm nginx

HOSTNAME=$(hostname)

sudo bash -c 'cat > /etc/nginx/sites-available/custom_header' <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By $HOSTNAME;
        root /usr/share/nginx/html;
        index index.html index.htm index.nginx-debian.html;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

sudo rm /etc/nginx/sites-enabled/default

sudo systemctl restart nginx

