#!/usr/bin/env bash
# Script that installs and configures HAProxy

# Install HAProxy
sudo pacman -Syu haproxy

# Enable HAProxy in the default configuration
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Create the HAProxy configuration directory if it doesn't exist
sudo mkdir -p /etc/haproxy

# Configure HAProxy
echo "
listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 111-web-01 [STUDENT_ID]-web-01:80 check
    server 111-web-02 [STUDENT_ID]-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

