#!/usr/bin/env bash
# Change your home IP
# Change localhost IP
# Change facebook IP

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
